In [1]:
import numpy as np
import pandas as pd
import matplotlib.image as image

In [2]:
import glob
path = "C:/Users/dguad/Documents/BdeB/AI/Courses/PROJET_SYNTHESE/ok_front"
file_list_test_ok = glob.glob(path + "/*.*")
path = "C:/Users/dguad/Documents/BdeB/AI/Courses/PROJET_SYNTHESE/def_front"
file_list_test_not_ok = glob.glob(path + "/*.*")

In [3]:
print(len(file_list_test_ok))
print(len(file_list_test_not_ok))

519
781

In [4]:
len(file_list_test_ok)

519

In [5]:
file_list_test_ok[0]

'C:/Users/dguad/Documents/BdeB/AI/Courses/PROJET_SYNTHESE/ok_front\\cast_ok_0_1018.jpeg'

In [11]:
import cv2
import collections
import matplotlib.image as image

df_ok = pd.DataFrame()

df_not_ok = pd.DataFrame()

In [15]:
indice = 0

for imag in file_list_test_ok:
    img=cv2.imread(imag)
    rows = []
    for i in range(512):
        for j in range(512):
            rows.append(img[i][j][0])

    number = dict(collections.Counter(rows))
    
    indice += 1
    df_ok = pd.concat([df_ok,pd.DataFrame(number,index=[indice])])

In [19]:
df_ok["Target"] = 1
df_ok

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,Target
1,9.0,6.0,4.0,7.0,9.0,16.0,17.0,20.0,29.0,40.0,...,13.0,7.0,13.0,10.0,7.0,10.0,2.0,7.0,14.0,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.0,54.0,64.0,73.0,53.0,66.0,82.0,67.0,232.0,1
3,3.0,3.0,11.0,8.0,18.0,35.0,88.0,137.0,243.0,431.0,...,12.0,9.0,3.0,3.0,3.0,5.0,2.0,5.0,5.0,1
4,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,5.0,...,21.0,10.0,11.0,4.0,13.0,10.0,7.0,9.0,12.0,1
5,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,2.0,...,1303.0,1238.0,1305.0,1313.0,1644.0,1109.0,1334.0,690.0,345.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,1.0,6.0,...,58.0,61.0,62.0,63.0,57.0,51.0,53.0,34.0,178.0,1
516,2.0,1.0,3.0,7.0,29.0,33.0,92.0,169.0,309.0,552.0,...,25.0,18.0,9.0,7.0,6.0,2.0,1.0,NaN,NaN,1
517,11.0,7.0,4.0,9.0,20.0,40.0,75.0,150.0,245.0,371.0,...,4.0,3.0,1.0,3.0,NaN,2.0,2.0,1.0,1.0,1
518,4.0,9.0,9.0,26.0,60.0,130.0,406.0,851.0,1557.0,1745.0,...,7.0,1.0,7.0,NaN,1.0,NaN,2.0,NaN,NaN,1
519,1.0,3.0,1.0,8.0,10.0,11.0,11.0,19.0,52.0,42.0,...,18.0,11.0,11.0,4.0,10.0,12.0,6.0,2.0,13.0,1

In [12]:
indice = 0

for imag in file_list_test_not_ok:
    img=cv2.imread(imag)
    rows = []
    for i in range(512):
        for j in range(512):
            rows.append(img[i][j][0])

    number = dict(collections.Counter(rows))
    
    indice += 1
    df_not_ok = pd.concat([df_not_ok,pd.DataFrame(number,index=[indice])])

In [21]:
df_not_ok["Target"] = 0
df_not_ok

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,Target
1,5.0,1.0,8.0,14.0,48.0,104.0,289.0,533.0,986.0,1414.0,...,6.0,4.0,2.0,2.0,1.0,1.0,NaN,NaN,1.0,0
2,2.0,2.0,3.0,6.0,11.0,21.0,64.0,138.0,329.0,743.0,...,10.0,5.0,11.0,5.0,4.0,2.0,2.0,1.0,7.0,0
3,8.0,4.0,8.0,17.0,37.0,127.0,276.0,609.0,1071.0,1466.0,...,11.0,2.0,2.0,2.0,NaN,NaN,1.0,NaN,1.0,0
4,6.0,2.0,11.0,15.0,45.0,72.0,156.0,291.0,574.0,901.0,...,56.0,50.0,41.0,25.0,11.0,18.0,9.0,8.0,14.0,0
5,NaN,NaN,7.0,12.0,18.0,40.0,129.0,255.0,354.0,632.0,...,3.0,NaN,2.0,1.0,1.0,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,NaN,NaN,1.0,NaN,1.0,NaN,2.0,3.0,1.0,4.0,...,615.0,612.0,510.0,768.0,168.0,145.0,126.0,145.0,245.0,0
778,11.0,4.0,16.0,23.0,61.0,141.0,344.0,669.0,1243.0,1894.0,...,44.0,36.0,22.0,15.0,14.0,10.0,4.0,1.0,10.0,0
779,NaN,1.0,5.0,9.0,27.0,55.0,205.0,518.0,851.0,1355.0,...,63.0,61.0,68.0,46.0,41.0,29.0,16.0,12.0,19.0,0
780,6.0,6.0,12.0,19.0,46.0,127.0,338.0,688.0,1200.0,1606.0,...,21.0,10.0,11.0,3.0,2.0,2.0,4.0,4.0,6.0,0
781,1.0,1.0,NaN,5.0,8.0,21.0,64.0,135.0,358.0,557.0,...,6.0,7.0,2.0,3.0,2.0,3.0,1.0,NaN,3.0,0

In [26]:
df_image = df_ok.append(df_not_ok, ignore_index=True)

In [27]:
df_image.fillna(0,inplace=True)
df_image

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,Target
0,9.0,6.0,4.0,7.0,9.0,16.0,17.0,20.0,29.0,40.0,...,13.0,7.0,13.0,10.0,7.0,10.0,2.0,7.0,14.0,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,53.0,54.0,64.0,73.0,53.0,66.0,82.0,67.0,232.0,1
2,3.0,3.0,11.0,8.0,18.0,35.0,88.0,137.0,243.0,431.0,...,12.0,9.0,3.0,3.0,3.0,5.0,2.0,5.0,5.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,5.0,...,21.0,10.0,11.0,4.0,13.0,10.0,7.0,9.0,12.0,1
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,...,1303.0,1238.0,1305.0,1313.0,1644.0,1109.0,1334.0,690.0,345.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,0.0,0.0,1.0,0.0,1.0,0.0,2.0,3.0,1.0,4.0,...,615.0,612.0,510.0,768.0,168.0,145.0,126.0,145.0,245.0,0
1296,11.0,4.0,16.0,23.0,61.0,141.0,344.0,669.0,1243.0,1894.0,...,44.0,36.0,22.0,15.0,14.0,10.0,4.0,1.0,10.0,0
1297,0.0,1.0,5.0,9.0,27.0,55.0,205.0,518.0,851.0,1355.0,...,63.0,61.0,68.0,46.0,41.0,29.0,16.0,12.0,19.0,0
1298,6.0,6.0,12.0,19.0,46.0,127.0,338.0,688.0,1200.0,1606.0,...,21.0,10.0,11.0,3.0,2.0,2.0,4.0,4.0,6.0,0
1299,1.0,1.0,0.0,5.0,8.0,21.0,64.0,135.0,358.0,557.0,...,6.0,7.0,2.0,3.0,2.0,3.0,1.0,0.0,3.0,0

In [31]:
from sklearn.utils import shuffle
df_image = shuffle(df_image)
df_image

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,Target
998,9.0,7.0,12.0,30.0,68.0,127.0,230.0,406.0,693.0,862.0,...,37.0,21.0,27.0,11.0,8.0,6.0,9.0,3.0,10.0,0
897,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,784.0,102.0,67.0,62.0,80.0,82.0,81.0,75.0,235.0,0
1061,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,2243.0,2285.0,1090.0,347.0,190.0,92.0,89.0,68.0,205.0,0
406,8.0,6.0,3.0,6.0,16.0,41.0,87.0,145.0,217.0,374.0,...,8.0,6.0,6.0,10.0,0.0,2.0,3.0,2.0,5.0,1
9,2.0,3.0,7.0,8.0,14.0,32.0,82.0,181.0,274.0,467.0,...,9.0,9.0,4.0,6.0,5.0,3.0,2.0,1.0,9.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,0.0,1.0,2.0,4.0,4.0,18.0,32.0,82.0,178.0,264.0,...,71.0,43.0,13.0,10.0,8.0,4.0,4.0,2.0,4.0,0
632,3.0,3.0,6.0,23.0,48.0,109.0,313.0,799.0,1368.0,1522.0,...,3.0,4.0,8.0,1.0,3.0,3.0,2.0,1.0,6.0,0
1263,0.0,4.0,2.0,7.0,16.0,36.0,92.0,208.0,363.0,673.0,...,24.0,23.0,14.0,11.0,9.0,10.0,3.0,8.0,16.0,0
935,11.0,6.0,14.0,22.0,51.0,124.0,197.0,357.0,665.0,865.0,...,42.0,35.0,27.0,27.0,17.0,18.0,13.0,9.0,19.0,0
694,4.0,6.0,10.0,29.0,41.0,107.0,354.0,733.0,1144.0,1586.0,...,11.0,7.0,5.0,6.0,5.0,7.0,0.0,1.0,5.0,0

In [33]:
df_image.to_csv("df_images.csv",index=False)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier